# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trytek Systems
email: stephen.murby@tryteksystems.co.uk
description: A personal blog following through my journey from a graduate software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tryteksystems.co.uk" # the base hostname & protocol for your site
twitter_username: stephen_murby
github_username:  stephen-murby

# Build settings
markdown: kramdown
